# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2896c968a9cbba1146dd4d4b4a69da9b44008602693abb44bd2676362afa3134720787ac8be3d24a1c3e003494cbb27b1f82dddfe12ec07ffb4c46285e92d2d8

test:
  secret_key_base: 49bf2f282f189ce4002dfa82cb4b0123be7d9e0d65539445a620f04b9a9ca301cf8c2bb5c163a6ff7aa1f4dcc2e6a58446de018b1533cedb1e022d230a8a7575

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
